//(infinitive, gerund, gerund_english)
var inf_gerES_gerEN = [
["abandonar","abandonando","abandoning"],
["abordar","abordando","boarding"],
["abortar","abortando","aborting"],
["abrazar","abrazando","hugging"],
["abrir","abriendo","opening"],
["aburrir","aburriendo","boring"],
["aburrirse","aburriéndose","getting bored"],
["abusar","abusando","going too far"],
["acabar","acabando","finishing"],
["acampar","acampando","camping"],
["aceptar","aceptando","accepting"],
["acercar","acercando","bringing near(er)"],
["acercarse","acercándose","approaching"],
["acompañar","acompañando","accompanying"],
["aconsejar","aconsejando","advising"],
["acontecer","aconteciendo","happening"],
["acordar","acordando","deciding"],
["acordarse","acordándose","remembering"],
["acortar","acortando","shortening"],
["acostar","acostando","putting to bed"],
["acostarse","acostándose","going to bed"],
["acostumbrar","acostumbrando","being accustomed to"],
["acostumbrarse","acostumbrándose","getting used to"],
["actuar","actuando","acting"],
["adivinar","adivinando","guessing"],
["admirar","admirando","admiring"],
["admitir","admitiendo","admitting"],
["adorar","adorando","adoring"],
["adornar","adornando","adorning"],
["advertir","advirtiendo","noticing"],
["afeitar","afeitando","shaving"],
["afeitarse","afeitándose","shaving"],
["afirmar","afirmando","making firm"],
["afligir","afligiendo","afflicting"],
["agorar","agorando","predicting"],
["agradar","agradando","pleasing"],
["agradecer","agradeciendo","being thankful for"],
["aguantar","aguantando","putting up with"],
["ahorcar","ahorcando","hanging"],
["ahorrar","ahorrando","saving"],
["alcanzar","alcanzando","reaching"],
["alegrar","alegrando","making happy"],
["alegrarse","alegrándose","being glad"],
["alentar","alentando","encouraging"],
["aliviar","aliviando","alleviating"],
["almorzar","almorzando","lunching"],
["alquilar","alquilando","renting"],
["amanecer","amaneciendo","dawning"],
["amar","amando","loving"],
["amenazar","amenazando","threatening"],
["andar","andando","walking"],
["anhelar","anhelando","be eager foring"],
["anunciar","anunciando","announcing"],
["añadir","añadiendo","adding"],
["apagar","apagando","extinguishing"],
["aparecer","apareciendo","appearing"],
["aplaudir","aplaudiendo","applauding"],
["aplicar","aplicando","applying"],
["apostar","apostando","betting"],
["apoyar","apoyando","supporting"],
["apreciar","apreciando","appreciating"],
["aprender","aprendiendo","learning"],
["apretar","apretando","being too tight"],
["aprobar","aprobando","passing"],
["arreglar","arreglando","arranging"],
["arrepentirse","arrepintiéndose","repenting"],
["arrojar","arrojando","throwing"],
["asistir","asistiendo","attending"],
["asociar","asociando","associating"],
["aspirar","aspirando","breathing in"],
["asustar","asustando","frightening"],
["asustarse","asustándose","being frightened"],
["atacar","atacando","attacking"],
["atender","atendiendo","attending to"],
["atraer","atrayendo","attracting"],
["atravesar","atravesando","crossing"],
["atreverse","atreviéndose","daring"],
["aumentar","aumentando","increasing"],
["avanzar","avanzando","advancing"],
["averiguar","averiguando","finding out"],
["avisar","avisando","warning"],
["ayudar","ayudando","helping"],
["bajar","bajando","lowering"],
["bañar","bañando","giving a bath"],
["bañarse","bañándose","taking a bath"],
["barrer","barriendo","sweeping"],
["batir","batiendo","beating"],
["bautizar","bautizando","baptizing"],
["beber","bebiendo","drinking"],
["bendecir","bendiciendo","blessing"],
["bordar","bordando","embroidering"],
["borrar","borrando","erasing"],
["brillar","brillando","shining"],
["brindar","brindando","toasting"],
["broncearse","bronceándose","getting a suntan"],
["bucear","buceando","skin-diving"],
["burlar","burlando","deceiving"],
["burlarse","burlándose","mocking"],
["buscar","buscando","searching for"],
["caber","cabiendo","fitting"],
["caer","cayendo","falling"],
["calcular","calculando","calculating"],
["calentar","calentando","heating"],
["calentarse","calentándose","getting heated"],
["callar","callando","keeping quiet about"],
["callarse","callándose","keeping quiet"],
["calmar","calmando","calming"],
["calmarse","calmándose","calming down"],
["caminar","caminando","walking"],
["cancelar","cancelando","cancelling"],
["cansar","cansando","tiring"],
["cansarse","cansándose","getting tired"],
["caracterizar","caracterizando","characterizing"],
["cargar","cargando","loading"],
["casar","casando","marrying"],
["casarse","casándose","marrying"],
["castigar","castigando","punishing"],
["causar","causando","causing"],
["cazar","cazando","hunting"],
["celebrar","celebrando","celebrating"],
["cenar","cenando","eating supper"],
["censurar","censurando","censoring"],
["cepillar","cepillando","brushing"],
["cerrar","cerrando","closing"],
["cesar","cesando","ceasing"],
["charlar","charlando","chatting"],
["chismear","chismeando","gossiping"],
["chocar","chocando","shocking"],
["civilizar","civilizando","civilizing"],
["clarificar","clarificando","clarifying"],
["clasificar","clasificando","classifying"],
["cobrar","cobrando","charging"],
["cocinar","cocinando","cooking"],
["coger","cogiendo","catching"],
["colgar","colgando","hanging"],
["colocar","colocando","locating"],
["colonizar","colonizando","colonizing"],
["combatir","combatiendo","combating"],
["comenzar","comenzando","beginning"],
["comer","comiendo","eating"],
["competir","compitiendo","competing"],
["componer","componiendo","composing"],
["comprar","comprando","buying"],
["comprender","comprendiendo","understanding"],
["comunicar","comunicando","communicating"],
["comunicarse","comunicándose","communicating"],
["condenar","condenando","condemning"],
["conducir","conduciendo","driving"],
["confesar","confesando","confessing"],
["confiar","confiando","trusting"],
["confirmar","confirmando","confirming"],
["compartir","compartiendo","sharing"],
["confiscar","confiscando","confiscating"],
["conjugar","conjugando","conjugating"],
["conocer","conociendo","knowing"],
["conquistar","conquistando","conquering"],
["conseguir","consiguiendo","getting"],
["consentir","consintiendo","consenting to"],
["conservar","conservando","preserving"],
["consistir","consistiendo","consisting"],
["constituir","constituyendo","constituting"],
["construir","construyendo","building"],
["consumir","consumiendo","consuming"],
["contaminar","contaminando","contaminating"],
["contar","contando","counting"],
["contener","conteniendo","containing"],
["contestar","contestando","answering"],
["continuar","continuando","continuing"],
["contribuir","contribuyendo","contributing"],
["controlar","controlando","controlling"],
["convencer","convenciendo","convincing"],
["convenir","conviniendo","agreeing"],
["conversar","conversando","talking"],
["convertir","convirtiendo","converting"],
["convidar","convidando","inviting"],
["copiar","copiando","copying"],
["corregir","corrigiendo","correcting"],
["correr","corriendo","running"],
["cortar","cortando","cutting"],
["coser","cosiendo","sewing"],
["costar","costando","costing"],
["crear","creando","creating"],
["crecer","creciendo","growing"],
["creer","creyendo","believing"],
["criar","criando","raising"],
["criarse","criándose","growing up"],
["criticar","criticando","criticizing"],
["crucificar","crucificando","crucifying"],
["cruzar","cruzando","crossing"],
["cubrir","cubriendo","covering"],
["cuidar","cuidando","taking care of"],
["culpar","culpando","blaming"],
["cultivar","cultivando","cultivating"],
["cumplir","cumpliendo","fulfilling"],
["curar","curando","curing"],
["dar","dando","giving"],
["deber","debiendo","owing"],
["decidir","decidiendo","deciding"],
["decidirse","decidiéndose","deciding"],
["decir","diciendo","saying"],
["declarar","declarando","declaring"],
["decorar","decorando","decorating"],
["dedicar","dedicando","dedicating"],
["dedicarse","dedicándose","devoting oneself"],
["defender","defendiendo","defending"],
["dejar","dejando","leaving"],
["demostrar","demostrando","demonstrating"],
["depender","dependiendo","depending"],
["depositar","depositando","depositing"],
["deprimir","deprimiendo","depressing"],
["derretir","derritiendo","melting"],
["desagradar","desagradando","displeasing"],
["desagradecer","desagradeciendo","being unthankful for"],
["desaparecer","desapareciendo","disappearing"],
["desayunar","desayunando","eating breakfast"],
["descansar","descansando","resting"],
["descender","descendiendo","descending"],
["describir","describiendo","describing"],
["descubrir","descubriendo","discovering"],
["desarrollar","desarrollando","developing"],
["desarrollarse","desarrollándose","developing"],
["desear","deseando","desiring"],
["deshacer","deshaciendo","undoing"],
["despedir","despidiendo","saying goodbye to"],
["despertar","despertando","awakening"],
["despertarse","despertándose","waking up"],
["destruir","destruyendo","destroying"],
["detener","deteniendo","stopping"],
["detenerse","deteniéndose","stopping"],
["detestar","detestando","detesting"],
["devolver","devolviendo","returning"],
["devorar","devorando","devouring"],
["dibujar","dibujando","drawing"],
["dirigir","dirigiendo","directing"],
["diseñar","diseñando","designing"],
["disfrutar","disfrutando","enjoying"],
["disgustar","disgustando","displeasing"],
["disminuir","disminuyendo","diminishing"],
["distinguir","distinguiendo","distinguishing"],
["distribuir","distribuyendo","distributing"],
["divertir","divirtiendo","amusing"],
["divertirse","divirtiéndose","having fun"],
["divorciar","divorciando","divorcing"],
["divorciarse","divorciándose","getting divorced"],
["doblar","doblando","doubling"],
["doler","doliendo","hurting"],
["dormir","durmiendo","sleeping"],
["dormirse","durmiéndose","going to sleep"],
["duchar","duchando","douching"],
["ducharse","duchándose","taking a shower"],
["dudar","dudando","doubting"],
["durar","durando","lasting"],
["echar","echando","throwing"],
["echarse","echándose","throwing oneself"],
["educar","educando","educating"],
["efectuar","efectuando","effecting"],
["ejercer","ejerciendo","exercising"],
["elegir","eligiendo","electing"],
["eliminar","eliminando","eliminating"],
["emborrachar","emborrachando","making drunk"],
["emborracharse","emborrachándose","getting drunk"],
["emigrar","emigrando","emigrating"],
["empezar","empezando","beginning"],
["emplear","empleando","employing"],
["enamorar","enamorando","inspiring love in"],
["enamorarse","enamorándose","falling in love"],
["encantar","encantando","delighting"],
["encender","encendiendo","burning"],
["encontrar","encontrando","finding"],
["enfadar","enfadando","angering"],
["enfadarse","enfadándose","getting angry"],
["enfermar","enfermando","making ill"],
["enfermarse","enfermándose","getting sick"],
["enflaquecer","enflaqueciendo","making thin"],
["enflaquecerse","enflaqueciéndose","getting thin"],
["engañar","engañando","deceiving"],
["enojar","enojando","angering"],
["enojarse","enojándose","getting angry"],
["enriquecer","enriqueciendo","enriching"],
["enriquecerse","enriqueciéndose","getting rich"],
["enseñar","enseñando","teaching"],
["ensuciar","ensuciando","dirtying"],
["entender","entendiendo","understanding"],
["enterarse","enterándose","finding out"],
["entrar","entrando","entering"],
["entregar","entregando","delivering"],
["entretener","entreteniendo","entertaining"],
["entrevistar","entrevistando","interviewing"],
["entusiasmar","entusiasmando","exciting"],
["entusiasmarse","entusiasmándose","getting excited"],
["envejecer","envejeciendo","aging"],
["envejecerse","envejeciéndose","getting old"],
["enviar","enviando","sending"],
["equivocar","equivocando","mistaking"],
["equivocarse","equivocándose","making a mistake"],
["errar","errando","erring"],
["escoger","escogiendo","choosing"],
["esconder","escondiendo","hiding"],
["esconderse","escondiéndose","hiding"],
["escribir","escribiendo","writing"],
["escuchar","escuchando","listening to"],
["esquiar","esquiando","skiing"],
["establecer","estableciendo","establishing"],
["estar","estando","being"],
["estimar","estimando","estimating"],
["estudiar","estudiando","studying"],
["evacuar","evacuando","evacuating"],
["evitar","evitando","avoiding"],
["exhibir","exhibiendo","exhibiting"],
["exigir","exigiendo","demanding"],
["explicar","explicando","explaining"],
["explorar","explorando","exploring"],
["explotar","explotando","exploiting"],
["exponer","exponiendo","exposing"],
["exportar","exportando","exporting"],
["expresar","expresando","expressing"],
["extender","extendiendo","extending"],
["extinguir","extinguiendo","extinguishing"],
["fabricar","fabricando","manufacturing"],
["faltar","faltando","lacking"],
["fascinar","fascinando","fascinating"],
["felicitar","felicitando","congratulating"],
["fijar","fijando","fixing"],
["fingir","fingiendo","faking"],
["firmar","firmando","signing"],
["florecer","floreciendo","flourishing"],
["formar","formando","forming"],
["fortalecer","fortaleciendo","fortifying"],
["freír","friendo","frying"],
["fumar","fumando","smoking"],
["funcionar","funcionando","functioning"],
["ganar","ganando","winning"],
["gastar","gastando","spending"],
["generalizar","generalizando","generalizing"],
["glorificar","glorificando","glorifying"],
["gobernar","gobernando","governing"],
["graduar","graduando","graduating"],
["graduarse","graduándose","graduating"],
["gritar","gritando","shouting"],
["gruñir","gruñendo","grunting"],
["guardar","guardando","guarding"],
["guiar","guiando","guiding"],
["gustar","gustando","pleasing"],
["hablar","hablando","speaking"],
["hacer","haciendo","doing"],
["hallar","hallando","finding"],
["hallarse","hallándose","being"],
["helar","helando","freezing"],
["heredar","heredando","inheriting"],
["herir","hiriendo","injuring"],
["hervir","hirviendo","boiling"],
["huir","huyendo","fleeing"],
["ilustrar","ilustrando","illustrating"],
["importar","importando","importing"],
["imprimir","imprimiendo","printing"],
["incluir","incluyendo","including"],
["indicar","indicando","indicating"],
["inducir","induciendo","inducing"],
["influir","influyendo","influencing"],
["informar","informando","informing"],
["iniciar","iniciando","initiating"],
["inmigrar","inmigrando","immigrating"],
["insistir","insistiendo","insisting"],
["instalar","instalando","installing"],
["insultar","insultando","insulting"],
["intentar","intentando","trying"],
["interesar","interesando","interesting"],
["interpretar","interpretando","interpreting"],
["introducir","introduciendo","introducing"],
["invadir","invadiendo","invading"],
["inventar","inventando","inventing"],
["invertir","invirtiendo","investing"],
["investigar","investigando","investigating"],
["invitar","invitando","inviting"],
["invocar","invocando","invoking"],
["ir","yendo","going"],
["irse","yéndose","going away"],
["jactarse","jactándose","boasting"],
["jugar","jugando","playing"],
["juntar","juntando","joining"],
["juntarse","juntándose","joining"],
["jurar","jurando","swearing"],
["ladrar","ladrando","barking"],
["lamentar","lamentando","lamenting"],
["lanzar","lanzando","throwing"],
["lastimar","lastimando","hurting"],
["lavar","lavando","washing"],
["lavarse","lavándose","washing up"],
["leer","leyendo","reading"],
["legalizar","legalizando","legalizing"],
["levantar","levantando","raising"],
["levantarse","levantándose","getting up"],
["limpiar","limpiando","cleaning"],
["llamar","llamando","calling"],
["llamarse","llamándose","being named"],
["llegar","llegando","arriving"],
["llenar","llenando","filling"],
["llevar","llevando","carrying"],
["llorar","llorando","crying"],
["llover","lloviendo","raining"],
["lograr","logrando","getting"],
["luchar","luchando","fighting"],
["madurar","madurando","maturing"],
["mandar","mandando","ordering"],
["manejar","manejando","driving"],
["mantener","manteniendo","maintaining"],
["maquillar","maquillando","putting make-up on"],
["maquillarse","maquillándose","putting on make-up"],
["marcar","marcando","marking"],
["masticar","masticando","chewing"],
["matar","matando","killing"],
["matricular","matriculando","registering"],
["matricularse","matriculándose","registering"],
["medir","midiendo","measuring"],
["mentir","mintiendo","lying"],
["merecer","mereciendo","deserving"],
["merendar","merendando","having a snack"],
["meter","metiendo","putting"],
["mezclar","mezclando","mixing"],
["mirar","mirando","watching"],
["modificar","modificando","modifying"],
["molestar","molestando","bothering"],
["montar","montando","mounting"],
["morir","muriendo","dying"],
["mostrar","mostrando","showing"],
["mover","moviendo","moving"],
["moverse","moviéndose","moving"],
["mudar(se)","mudando","moving"],
["mudarse","mudándose","moving"],
["nacer","naciendo","being born"],
["nadar","nadando","swimming"],
["navegar","navegando","navigating"],
["necesitar","necesitando","needing"],
["negar","negando","denying"],
["negarse","negándose","refusing"],
["negociar","negociando","negotiating"],
["nevar","nevando","snowing"],
["notar","notando","noting"],
["obedecer","obedeciendo","obeying"],
["obligar","obligando","obliging"],
["obtener","obteniendo","obtaining"],
["ocurrir","ocurriendo","occurring"],
["odiar","odiando","hating"],
["ofender","ofendiendo","offending"],
["ofrecer","ofreciendo","offering"],
["oír","oyendo","hearing"],
["oler","oliendo","smelling"],
["olvidar","olvidando","forgetting"],
["olvidarse","olvidándose","forgetting"],
["oponer","oponiendo","pitting"],
["oponerse","oponiéndose","putting on"],
["organizar","organizando","organizing"],
["padecer","padeciendo","suffering"],
["pagar","pagando","paying"],
["parar","parando","stopping"],
["parecer","pareciendo","seeming"],
["participar","participando","participating"],
["pasar","pasando","passing"],
["patinar","patinando","skating"],
["pedir","pidiendo","requesting"],
["pegar","pegando","sticking"],
["peinar","peinando","combing"],
["peinarse","peinándose","combing my hair"],
["pelear","peleando","fighting"],
["pensar","pensando","thinking"],
["perder","perdiendo","losing"],
["perdonar","perdonando","forgiving"],
["permanecer","permaneciendo","staying"],
["permitir","permitiendo","permitting"],
["perseguir","persiguiendo","pursuing"],
["pertenecer","perteneciendo","belonging"],
["pesar","pesando","weighing"],
["pescar","pescando","fishing"],
["picar","picando","pricking"],
["pintar","pintando","painting"],
["platicar","platicando","chatting"],
["planchar","planchando","ironing"],
["plantar","plantando","planting"],
["poder","pudiendo","being able"],
["poner","poniendo","puting"],
["ponerse","poniéndose","putting on"],
["practicar","practicando","practicing"],
["predecir","prediciendo","predicting"],
["preferir","prefiriendo","preferring"],
["preguntar","preguntando","asking"],
["preguntarse","preguntándose","wondering"],
["preparar","preparando","preparing"],
["prepararse","preparándose","getting ready"],
["presentir","presintiendo","having a premonition of"],
["preservar","preservando","preserving"],
["prever","previendo","foreseeing"],
["probar","probando","tasting"],
["producir","produciendo","producing"],
["prohibir","prohibiendo","prohibiting"],
["prometer","prometiendo","promising"],
["proponer","proponiendo","proposing"],
["proseguir","prosiguiendo","continuing"],
["proteger","protegiendo","protecting"],
["protestar","protestando","protesting"],
["provocar","provocando","provoking"],
["publicar","publicando","publishing"],
["purificar","purificando","purifying"],
["quebrar","quebrando","breaking"],
["quebrarse","quebrándose","breaking"],
["quedar","quedando","staying"],
["quedarse","quedándose","staying"],
["quejarse","quejándose","complaining"],
["quemar","quemando","burning"],
["quemarse","quemándose","burning up"],
["querer","queriendo","wanting"],
["realizar","realizando","achieving"],
["rechazar","rechazando","rejecting"],
["recibir","recibiendo","receiving"],
["reciclar","reciclando","recycling"],
["recoger","recogiendo","picking up"],
["recomendar","recomendando","recommending"],
["reconocer","reconociendo","recognizing"],
["recordar","recordando","remembering"],
["reducir","reduciendo","reducing"],
["regalar","regalando","giving"],
["regar","regando","watering"],
["regatear","regateando","haggling"],
["regir","rigiendo","ruling"],
["registrar","registrando","registering"],
["registrarse","registrándose","registering"],
["regresar","regresando","returning"],
["regular","regulando","regulating"],
["rehusar","rehusando","refusing"],
["reinar","reinando","reigning"],
["reír","riendo","laughing"],
["renacer","renaciendo","being reborn"],
["renovar","renovando","renewing"],
["renunciar","renunciando","renouncing"],
["reñir","riñendo","quarreling"],
["reparar","reparando","repairing"],
["repasar","repasando","reviewing"],
["repetir","repitiendo","repeating"],
["replicar","replicando","replying"],
["reportar","reportando","bringing"],
["requerir","requiriendo","requiring"],
["reservar","reservando","reserving"],
["resolver","resolviendo","solving"],
["respetar","respetando","respecting"],
["respirar","respirando","breathing"],
["responder","respondiendo","responding"],
["resultar","resultando","turning out"],
["revelar","revelando","revealing"],
["rezar","rezando","praying"],
["robar","robando","robbing"],
["rogar","rogando","pleading"],
["romper","rompiendo","breaking"],
["saber","sabiendo","knowing"],
["sacar","sacando","taking out"],
["sacrificar","sacrificando","sacrificing"],
["sacudir","sacudiendo","shaking"],
["salir","saliendo","leaving"],
["saltar","saltando","jumping"],
["saludar","saludando","greeting"],
["salvar","salvando","saving"],
["satisfacer","satisfaciendo","satisfying"],
["satirizar","satirizando","satirizing"],
["secar","secando","drying"],
["secarse","secándose","drying"],
["seguir","siguiendo","following"],
["sentar","sentando","seating"],
["sentarse","sentándose","sitting down"],
["sentir","sintiendo","feeling"],
["sentirse","sintiéndose","feeling"],
["señalar","señalando","pointing out"],
["ser","siendo","being"],
["servir","sirviendo","serving"],
["significar","significando","signifying"],
["simbolizar","simbolizando","symbolizing"],
["situar","situando","placing"],
["sobrevivir","sobreviviendo","surviving"],
["soler","soliendo","being accustomed to"],
["sonar","sonando","sounding"],
["soñar","soñando","dreaming"],
["sonreír","sonriendo","smiling"],
["soportar","soportando","supporting"],
["sorprender","sorprendiendo","surprising"],
["subir","subiendo","going up"],
["suceder","sucediendo","happening"],
["sufrir","sufriendo","suffering"],
["sugerir","sugiriendo","suggesting"],
["suponer","suponiendo","supposing"],
["surgir","surgiendo","arising"],
["suspirar","suspirando","sighing"],
["sustituir","sustituyendo","substituting"],
["tañer","tañendo","playing"],
["tapar","tapando","covering"],
["tardar","tardando","delaying"],
["temer","temiendo","fearing"],
["tener","teniendo","having"],
["teñir","tiñendo","dyeing"],
["terminar","terminando","finishing"],
["tirar","tirando","throwing"],
["tocar","tocando","touching"],
["tomar","tomando","taking"],
["torcer","torciendo","twisting"],
["toser","tosiendo","coughing"],
["trabajar","trabajando","working"],
["traducir","traduciendo","translating"],
["traer","trayendo","bringing"],
["tragar","tragando","swallowing"],
["tratar","tratando","treating"],
["triunfar","triunfando","triumphing"],
["tropezar","tropezando","tripping"],
["ubicar","ubicando","placing"],
["unir","uniendo","uniting"],
["untar","untando","anointing"],
["usar","usando","using"],
["utilizar","utilizando","using"],
["vaciar","vaciando","emptying"],
["valer","valiendo","being worth"],
["variar","variando","varying"],
["vencer","venciendo","conquering"],
["vender","vendiendo","selling"],
["venir","viniendo","coming"],
["ver","viendo","seeing"],
["verificar","verificando","verifying"],
["vestir","vistiendo","dressing"],
["vestirse","vistiéndose","getting dressed"],
["viajar","viajando","traveling"],
["violar","violando","violating"],
["visitar","visitando","visiting"],
["vivir","viviendo","living"],
["volar","volando","flying"],
["volver","volviendo","returning"],
["vomit","vomitando","vomiting"],
["votar","votando","voting"],
["yacer","yaciendo","lying"],
["zambullirse","zambulléndose","diving"],
["besar","besando","kissing"],
["bailar","bailando","dancing"],
["presentar","presentando","introducing"],
["esperar","esperando","hoping"]];

console.log(inf_gerES_gerEN.length);
