//(infinitive, pastparticiple, pastparticiple_english)
var inf_pastpartES_pastpartEN = [
["abandonar","abandonado","abandoned"],
["abordar","abordado","boarded"],
["abortar","abortado","aborted"],
["abrazar","abrazado","hugged"],
["abrir","abierto","opened"],
["aburrir","aburrido","bored"],
["aburrirse","aburrido","bored"],
["abusar","abusado","gone too far, abused"],
["acabar","acabado","finished"],
["acampar","acampado","camped"],
["aceptar","aceptado","accepted"],
["acercar","acercado","brought near(er)"],
["acercarse","acercado","approached"],
["acompañar","acompañado","accompanied"],
["aconsejar","aconsejado","advisedn"],
["acontecer","acontecido","happened"],
["acordar","acordado","decided"],
["acordarse","acordado","remembered"],
["acortar","acortado","shortened"],
["acostar","acostado","put to bed"],
["acostarse","acostado","gone to bed"],
["acostumbrar","acostumbrado","been accustomed to"],
["acostumbrarse","acostumbrado","got used to"],
["actuar","actuado","acted"],
["adivinar","adivinado","guessed"],
["admirar","admirado","admired"],
["admitir","admitido","admitted"],
["adorar","adorado","adored"],
["adornar","adornado","adorned"],
["advertir","advertido","noticed"],
["afeitar","afeitado","shaved"],
["afeitarse","afeitado","shaved"],
["afirmar","afirmado","made firm"],
["afligir","afligido","afflicted"],
["agorar","agorado","predicted"],
["agradar","agradado","pleased"],
["agradecer","agradecido","thankful for"],
["aguantar","aguantado","put up with"],
["ahorcar","ahorcado","hanged"],
["ahorrar","ahorrado","saved"],
["alcanzar","alcanzado","reached"],
["alegrar","alegrado","made happy"],
["alegrarse","alegrado","been glad"],
["alentar","alentado","encouraged"],
["aliviar","aliviado","alleviated"],
["almorzar","almorzado","lunched"],
["alquilar","alquilado","rented"],
["amanecer","amanecido","dawned"],
["amar","amado","loved"],
["amenazar","amenazado","threatened"],
["andar","andado","walked"],
["anhelar","anhelado","eager for"],
["anunciar","anunciado","announced"],
["añadir","añadido","added"],
["apagar","apagado","extinguished"],
["aparecer","aparecido","appeared"],
["aplaudir","aplaudido","applauded"],
["aplicar","aplicado","applied"],
["apostar","apostado","bet"],
["apoyar","apoyado","supported"],
["apreciar","apreciado","appreciated"],
["aprender","aprendido","learned"],
["apretar","apretado","was too tight"],
["aprobar","aprobado","passed"],
["arreglar","arreglado","arranged"],
["arrepentirse","arrepentido","repented"],
["arrojar","arrojado","thrown"],
["asistir","asistido","attended"],
["asociar","asociado","associated"],
["aspirar","aspirado","breathed in"],
["asustar","asustado","frightened"],
["asustarse","asustado","frightened"],
["atacar","atacado","attacked"],
["atender","atendido","attended to"],
["atraer","atraído","attracted"],
["atravesar","atravesado","crossed"],
["atreverse","atrevido","dared"],
["aumentar","aumentado","increased"],
["avanzar","avanzado","advanced"],
["averiguar","averiguado","found out"],
["avisar","avisado","warned"],
["ayudar","ayudado","helped"],
["bajar","bajado","lowered"],
["bañar","bañado","given a bath"],
["bañarse","bañado","bathed, taken a bath"],
["barrer","barrido","swept"],
["batir","batido","beat"],
["bautizar","bautizado","baptized"],
["beber","bebido","drunk"],
["bendecir","bendito","blessed"],
["bordar","bordado","embroidered"],
["borrar","borrado","erased"],
["brillar","brillado","shone"],
["brindar","brindado","toasted"],
["broncearse","bronceado","got a suntan"],
["bucear","buceado","skin-dived"],
["burlar","burlado","deceived"],
["burlarse","burlado","mocked"],
["buscar","buscado","searched for"],
["caber","cabido","fit"],
["caer","caído","fallen"],
["calcular","calculado","calculated"],
["calentar","calentado","heated"],
["calentarse","calentado","heated"],
["callar","callado","kept quiet about"],
["callarse","callado","quiet"],
["calmar","calmado","calm"],
["calmarse","calmado","calm"],
["caminar","caminado","walked"],
["cancelar","cancelado","cancelled"],
["cansar","cansado","tired"],
["cansarse","cansado","tired"],
["caracterizar","caracterizado","characterized"],
["cargar","cargado","loaded"],
["casar","casado","married"],
["casarse","casado","married"],
["castigar","castigado","punished"],
["causar","causado","caused"],
["cazar","cazado","hunted"],
["celebrar","celebrado","celebrated"],
["cenar","cenado","eaten supper"],
["censurar","censurado","censored"],
["cepillar","cepillado","brushed"],
["cerrar","cerrado","closed"],
["cesar","cesado","ceased"],
["charlar","charlado","chatted"],
["chismear","chismeado","gossiped"],
["chocar","chocado","shocked"],
["civilizar","civilizado","civilized"],
["clarificar","clarificado","clarified"],
["clasificar","clasificado","classified"],
["cobrar","cobrado","charged"],
["cocinar","cocinado","cooked"],
["coger","cogido","caught"],
["colgar","colgado","hung"],
["colocar","colocado","located"],
["colonizar","colonizado","colonized"],
["combatir","combatido","combated"],
["comenzar","comenzado","begun"],
["comer","comido","eaten"],
["competir","competido","competed"],
["componer","compuesto","composed"],
["comprar","comprado","bought"],
["comprender","comprendido","understood"],
["comunicar","comunicado","communicated"],
["comunicarse","comunicado","communicated"],
["condenar","condenado","condemned"],
["conducir","conducido","driven"],
["confesar","confesado","confessed"],
["confiar","confiado","trusted"],
["confirmar","confirmado","confirmed"],
["compartir","compartido","shared"],
["confiscar","confiscado","confiscated"],
["conjugar","conjugado","conjugated"],
["conocer","conocido","known"],
["conquistar","conquistado","conquered"],
["conseguir","conseguido","gotten"],
["consentir","consentido","consented to"],
["conservar","conservado","preserved"],
["consistir","consistido","consisted"],
["constituir","constituido","constituted"],
["construir","construido","built"],
["consumir","consumido","consumed"],
["contaminar","contaminado","contaminated"],
["contar","contado","counted"],
["contener","contenido","contained"],
["contestar","contestado","answered"],
["continuar","continuado","continued"],
["contribuir","contribuido","contributed"],
["controlar","controlado","controlled"],
["convencer","convencido","convinced"],
["convenir","convenido","agreed"],
["conversar","conversado","talked"],
["convertir","convertido","converted"],
["convidar","convidado","invited"],
["copiar","copiado","copied"],
["corregir","corregido","corrected"],
["correr","corrido","run"],
["cortar","cortado","cut"],
["coser","cosido","sewed"],
["costar","costado","cost"],
["crear","creado","created"],
["crecer","crecido","grown"],
["creer","creído","believed"],
["criar","criado","raised"],
["criarse","criado","grown up"],
["criticar","criticado","criticized"],
["crucificar","crucificado","crucified"],
["cruzar","cruzado","crossed"],
["cubrir","cubierto","covered"],
["cuidar","cuidado","taken care of"],
["culpar","culpado","blamed"],
["cultivar","cultivado","cultivated"],
["cumplir","cumplido","fulfilled"],
["curar","curado","cured"],
["dar","dado","given"],
["deber","debido","owed"],
["decidir","decidido","decided"],
["decidirse","decidido","decided"],
["decir","dicho","said"],
["declarar","declarado","declared"],
["decorar","decorado","decorated"],
["dedicar","dedicado","dedicated"],
["dedicarse","dedicado","devoted"],
["defender","defendido","defended"],
["dejar","dejado","left"],
["demostrar","demostrado","demonstrated"],
["depender","dependido","depended"],
["depositar","depositado","deposited"],
["deprimir","deprimido","depressed"],
["derretir","derretido","melted"],
["desagradar","desagradado","displeased"],
["desagradecer","desagradecido","unthankful for"],
["desaparecer","desaparecido","disappeared"],
["desayunar","desayunado","eaten breakfast"],
["descansar","descansado","rested"],
["descender","descendido","descended"],
["describir","descrito","described"],
["descubrir","descubierto","discovered"],
["desarrollar","desarrollado","developed"],
["desarrollarse","desarrollado","developed"],
["desear","deseado","desired"],
["deshacer","deshecho","undone"],
["despedir","despedido","said goodbye to"],
["despertar","despertado","awakened"],
["despertarse","despertado","waken up"],
["destruir","destruido","destroyed"],
["detener","detenido","stopped"],
["detenerse","detenido","stopped"],
["detestar","detestado","detested"],
["devolver","devuelto","returned"],
["devorar","devorado","devoured"],
["dibujar","dibujado","drawn"],
["dirigir","dirigido","directed"],
["diseñar","diseñado","designed"],
["disfrutar","disfrutado","enjoyed"],
["disgustar","disgustado","displeased"],
["disminuir","disminuido","diminished"],
["distinguir","distinguido","distinguished"],
["distribuir","distribuido","distributed"],
["divertir","divertido","amused"],
["divertirse","divertido","fun, had fun"],
["divorciar","divorciado","divorced"],
["divorciarse","divorciado","gotten divorced"],
["doblar","doblado","doubled"],
["doler","dolido","hurt"],
["dormir","dormido","slept"],
["dormirse","dormido","asleep, gone to sleep"],
["duchar","duchado","douched"],
["ducharse","duchado","showered, taken a shower"],
["dudar","dudado","doubted"],
["durar","durado","lasted"],
["echar","echado","thrown"],
["echarse","echado","thrown"],
["educar","educado","educated"],
["efectuar","efectuado","effected"],
["ejercer","ejercido","exercised"],
["elegir","elegido","elected"],
["eliminar","eliminado","eliminated"],
["emborrachar","emborrachado","made drunk"],
["emborracharse","emborrachado","drunk"],
["emigrar","emigrado","emigrated"],
["empezar","empezado","begun"],
["emplear","empleado","employed"],
["enamorar","enamorado","inspired love in"],
["enamorarse","enamorado","fell in love"],
["encantar","encantado","delighted"],
["encender","encendido","burnt"],
["encontrar","encontrado","found"],
["enfadar","enfadado","angered"],
["enfadarse","enfadado","angry"],
["enfermar","enfermado","made ill"],
["enfermarse","enfermado","sickened, sick"],
["enflaquecer","enflaquecido","made thin"],
["enflaquecerse","enflaquecido","thin, gotten thin"],
["engañar","engañado","deceived"],
["enojar","enojado","angered"],
["enojarse","enojado","angry"],
["enriquecer","enriquecido","enriched"],
["enriquecerse","enriquecido","rich, gotten rich"],
["enseñar","enseñado","taught"],
["ensuciar","ensuciado","dirtied"],
["entender","entendido","understood"],
["enterarse","enterado","found out"],
["entrar","entrado","entered"],
["entregar","entregado","delivered"],
["entretener","entretenido","entertained"],
["entrevistar","entrevistado","interviewed"],
["entusiasmar","entusiasmado","excited"],
["entusiasmarse","entusiasmado","got excited"],
["envejecer","envejecido","aged"],
["envejecerse","envejecido","old, gotten old"],
["enviar","enviado","sent"],
["equivocar","equivocado","mistaken"],
["equivocarse","equivocado","made a mistake"],
["errar","errado","erred"],
["escoger","escogido","chosen"],
["esconder","escondido","hiddenk"],
["esconderse","escondido","fun, hid"],
["escribir","escrito","written"],
["escuchar","escuchado","listened to"],
["esquiar","esquiado","skied"],
["establecer","establecido","established"],
["estar","estado","been"],
["estimar","estimado","estimated"],
["estudiar","estudiado","studied"],
["evacuar","evacuado","evacuated"],
["evitar","evitado","avoided"],
["exhibir","exhibido","exhibited"],
["exigir","exigido","demanded"],
["explicar","explicado","explained"],
["explorar","explorado","explored"],
["explotar","explotado","exploited"],
["exponer","expuesto","exposed"],
["exportar","exportado","exported"],
["expresar","expresado","expressed"],
["extender","extendido","extended"],
["extinguir","extinguido","extinguished"],
["fabricar","fabricado","manufactured"],
["faltar","faltado","lacked"],
["fascinar","fascinado","fascinated"],
["felicitar","felicitado","congratulated"],
["fijar","fijado","fixed"],
["fingir","fingido","faked"],
["firmar","firmado","signed"],
["florecer","florecido","flourished"],
["formar","formado","formed"],
["fortalecer","fortalecido","fortified"],
["freír","frito","fried"],
["fumar","fumado","smoked"],
["funcionar","funcionado","functioned"],
["ganar","ganado","won"],
["gastar","gastado","spent"],
["generalizar","generalizado","generalized"],
["glorificar","glorificado","glorified"],
["gobernar","gobernado","governed"],
["graduar","graduado","graduated"],
["graduarse","graduado","graduated"],
["gritar","gritado","shouted"],
["gruñir","gruñido","grunted"],
["guardar","guardado","guarded"],
["guiar","guiado","guided"],
["gustar","gustado","pleased"],
["hablar","hablado","spoken"],
["hacer","hecho","done"],
["hallar","hallado","found"],
["hallarse","hallado","been, found"],
["helar","helado","frozen"],
["heredar","heredado","inherited"],
["herir","herido","injured"],
["hervir","hervido","boiled"],
["huir","huido","fled"],
["ilustrar","ilustrado","illustrated"],
["importar","importado","imported"],
["imprimir","imprimido, impreso","printed"],
["incluir","incluido","included"],
["indicar","indicado","indicated"],
["inducir","inducido","induced"],
["influir","influido","influenced"],
["informar","informado","informed"],
["iniciar","iniciado","initiated"],
["inmigrar","inmigrado","immigratingd"],
["insistir","insistido","insisted"],
["instalar","instalado","installed"],
["insultar","insultado","insulted"],
["intentar","intentado","tried"],
["interesar","interesado","interested"],
["interpretar","interpretado","interpreted"],
["introducir","introducido","introduced"],
["invadir","invadido","invaded"],
["inventar","inventado","invented"],
["invertir","invertido","invested"],
["investigar","investigado","investigated"],
["invitar","invitado","invited"],
["invocar","invocado","invoked"],
["ir","ido","gone"],
["irse","ido","gone away"],
["jactarse","jactado","boasted"],
["jugar","jugado","played"],
["juntar","juntado","joined"],
["juntarse","juntado","joined"],
["jurar","jurado","sworn"],
["ladrar","ladrado","barked"],
["lamentar","lamentado","lamented"],
["lanzar","lanzado","thrown"],
["lastimar","lastimado","hurt"],
["lavar","lavado","washed"],
["lavarse","lavado","washed up"],
["leer","leído","read"],
["legalizar","legalizado","legalized"],
["levantar","levantado","raised"],
["levantarse","levantado","gotten up"],
["limpiar","limpiado","cleaned"],
["llamar","llamado","called"],
["llamarse","llamado","named"],
["llegar","llegado","arrived"],
["llenar","llenado","filled"],
["llevar","llevado","carried"],
["llorar","llorado","cried"],
["llover","llovido","rained"],
["lograr","logrado","got"],
["luchar","luchado","fought"],
["madurar","madurado","matured"],
["mandar","mandado","ordered"],
["manejar","manejado","driven"],
["mantener","mantenido","maintained"],
["maquillar","maquillado","put make-up on"],
["maquillarse","maquillado","put on make-up"],
["marcar","marcado","marked"],
["masticar","masticado","chewed"],
["matar","matado","killed"],
["matricular","matriculado","registered"],
["matricularse","matriculado","registered"],
["medir","medido","measured"],
["mentir","mentido","lied"],
["merecer","merecido","deserved"],
["merendar","merendado","had a snack"],
["meter","metido","put"],
["mezclar","mezclado","mixed"],
["mirar","mirado","watched"],
["modificar","modificado","modified"],
["molestar","molestado","bothered"],
["montar","montado","mounted"],
["morir","muerto","died"],
["mostrar","mostrado","shown"],
["mover","movido","moved"],
["moverse","movido","moved"],
["mudar(se)","mudado","moved"],
["mudarse","mudado","moved"],
["nacer","nacido","(been) born"],
["nadar","nadado","swum"],
["navegar","navegado","navigated"],
["necesitar","necesitado","needed"],
["negar","negado","denied"],
["negarse","negado","refused"],
["negociar","negociado","negotiated"],
["nevar","nevado","snowed"],
["notar","notado","noted"],
["obedecer","obedecido","obeyed"],
["obligar","obligado","obliged"],
["obtener","obtenido","obtained"],
["ocurrir","ocurrido","occurred"],
["odiar","odiado","hated"],
["ofender","ofendido","offended"],
["ofrecer","ofrecido","offered"],
["oír","oído","heard"],
["oler","olido","smelled"],
["olvidar","olvidado","forgotten"],
["olvidarse","olvidado","forgot"],
["oponer","opuesto","pitted"],
["oponerse","opuesto","put on"],
["organizar","organizado","organized"],
["padecer","padecido","suffered"],
["pagar","pagado","paid"],
["parar","parado","stopped"],
["parecer","parecido","seemed"],
["participar","participado","participated"],
["pasar","pasado","passed"],
["patinar","patinado","skated"],
["pedir","pedido","requested"],
["pegar","pegado","stuck"],
["peinar","peinado","combed"],
["peinarse","peinado","combed my hair"],
["pelear","peleado","fought"],
["pensar","pensado","thought"],
["perder","perdido","lost"],
["perdonar","perdonado","forgiven"],
["permanecer","permanecido","stayed"],
["permitir","permitido","permitted"],
["perseguir","perseguido","pursued"],
["pertenecer","pertenecido","belonged"],
["pesar","pesado","weighed"],
["pescar","pescado","fished"],
["picar","picado","pricked"],
["pintar","pintado","painted"],
["platicar","platicado","chatted"],
["planchar","planchado","ironed"],
["plantar","plantado","planted"],
["poder","podido","been able"],
["poner","puesto","put"],
["ponerse","puesto","put on"],
["practicar","practicado","practiced"],
["predecir","predicho","predicted"],
["preferir","preferido","preferred"],
["preguntar","preguntado","asked"],
["preguntarse","preguntado","wondered"],
["preparar","preparado","prepared"],
["prepararse","preparado","gotten ready"],
["presentir","presentido","had a premonition of"],
["preservar","preservado","preserved"],
["prever","previsto","foreseen"],
["probar","probado","tasted"],
["producir","producido","produced"],
["prohibir","prohibido","prohibited"],
["prometer","prometido","promised"],
["proponer","propuesto","proposed"],
["proseguir","proseguido","continued"],
["proteger","protegido","protected"],
["protestar","protestado","protested"],
["provocar","provocado","provoked"],
["publicar","publicado","published"],
["purificar","purificado","purified"],
["quebrar","quebrado","broken"],
["quebrarse","quebrado","broken"],
["quedar","quedado","stayed"],
["quedarse","quedado","stayed"],
["quejarse","quejado","complained"],
["quemar","quemado","burned"],
["quemarse","quemado","burned up"],
["querer","querido","wanted"],
["realizar","realizado","achieved"],
["rechazar","rechazado","rejected"],
["recibir","recibido","received"],
["reciclar","reciclado","recycled"],
["recoger","recogido","picked up"],
["recomendar","recomendado","recommended"],
["reconocer","reconocido","recognized"],
["recordar","recordado","remembered"],
["reducir","reducido","reduced"],
["regalar","regalado","given"],
["regar","regado","watered"],
["regatear","regateado","haggled"],
["regir","regido","ruled"],
["registrar","registrado","registered"],
["registrarse","registrado","registered"],
["regresar","regresado","returned"],
["regular","regulado","regulated"],
["rehusar","rehusado","refused"],
["reinar","reinado","reigned"],
["reír","reído","laughed"],
["renacer","renacido","(been) reborn"],
["renovar","renovado","renewed"],
["renunciar","renunciado","renounced"],
["reñir","reñido","quarreled"],
["reparar","reparado","repaired"],
["repasar","repasado","reviewed"],
["repetir","repetido","repeated"],
["replicar","replicado","replied"],
["reportar","reportado","brought"],
["requerir","requerido","required"],
["reservar","reservado","reserved"],
["resolver","resuelto","solved"],
["respetar","respetado","respected"],
["respirar","respirado","breathed"],
["responder","respondido","responded"],
["resultar","resultado","turned out"],
["revelar","revelado","revealed"],
["rezar","rezado","prayed"],
["robar","robado","robbed"],
["rogar","rogado","pleaded"],
["romper","roto","broken"],
["saber","sabido","known"],
["sacar","sacado","taken out"],
["sacrificar","sacrificado","sacrificed"],
["sacudir","sacudido","shook"],
["salir","salido","left"],
["saltar","saltado","jumped"],
["saludar","saludado","greeted"],
["salvar","salvado","saved"],
["satisfacer","satisfecho","satisfied"],
["satirizar","satirizado","satirized"],
["secar","secado","dried"],
["secarse","secado","dried"],
["seguir","seguido","followed"],
["sentar","sentado","seated"],
["sentarse","sentado","seated, sat down"],
["sentir","sentido","felt"],
["sentirse","sentido","felt"],
["señalar","señalado","pointed out"],
["ser","sido","been"],
["servir","servido","served"],
["significar","significado","signified"],
["simbolizar","simbolizado","symbolized"],
["situar","situado","placed"],
["sobrevivir","sobrevivido","survived"],
["soler","solido","accustomed to"],
["sonar","sonado","sounded"],
["soñar","soñado","dreamed"],
["sonreír","sonreído","smiled"],
["soportar","soportado","supported"],
["sorprender","sorprendido","surprised"],
["subir","subido","went up"],
["suceder","sucedido","happened"],
["sufrir","sufrido","suffered"],
["sugerir","sugerido","suggested"],
["suponer","supuesto","supposed"],
["surgir","surgido","arisen"],
["suspirar","suspirado","sighed"],
["sustituir","sustituido","substituted"],
["tañer","tañido","played"],
["tapar","tapado","covered"],
["tardar","tardado","delayed"],
["temer","temido","feared"],
["tener","tenido","had"],
["teñir","teñido","dyed"],
["terminar","terminado","finished"],
["tirar","tirado","thrown"],
["tocar","tocado","touched"],
["tomar","tomado","taken"],
["torcer","torcido","twisted"],
["toser","tosido","coughed"],
["trabajar","trabajado","worked"],
["traducir","traducido","translated"],
["traer","traído","brought"],
["tragar","tragado","swallowed"],
["tratar","tratado","treated"],
["triunfar","triunfado","triumphed"],
["tropezar","tropezado","tripped"],
["ubicar","ubicado","placed"],
["unir","unido","united"],
["untar","untado","anointed"],
["usar","usado","used"],
["utilizar","utilizado","used"],
["vaciar","vaciado","emptied"],
["valer","valido","been worth"],
["variar","variado","varied"],
["vencer","vencido","conquered"],
["vender","vendido","sold"],
["venir","venido","come"],
["ver","visto","seen"],
["verificar","verificado","verified"],
["vestir","vestido","dressed"],
["vestirse","vestido","dressed, gotten dressed"],
["viajar","viajado","traveled"],
["violar","violado","violated"],
["visitar","visitado","visited"],
["vivir","vivido","lived"],
["volar","volado","flown"],
["volver","vuelto","returned"],
["vomit","vomitado","vomited"],
["votar","votado","voted"],
["yacer","yacido","lain/laid"],
["zambullirse","zambullido","dove"],
["besar","besado","kissed"],
["bailar","bailado","danced"],
["presentar","presentado","introduced"],
["esperar","esperado","hoped"]];
